import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Mode from "@/components/darkMode";
import Footer from "@/components/footer/footer";
import Herosec from "@/components/herosec/herosec";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${Mode}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} max-w-[1300px] mx-auto dark:text-gray-300 dark:bg-[#090d1f] antialiased`}
      >
        <Header />
        <Herosec/>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
